In [6]:
l=range(1000000)

In [1]:
import numpy as np

In [8]:
arr=np.arange(1000000)

In [9]:
%time for i in range(1,10): resultant= [x*3 for x in l ]

Wall time: 1.57 s


In [10]:
%time for i in range(1,10): resultant= arr*3 #fast due to contigous memory storage in numpy 

Wall time: 53.3 ms


# This shows in above situaation how much fast is NumPy 

In [13]:
x=np.zeros((3,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.empty((3,3)) #random numbers form memory are put in array 

array([[0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 4.17e-321],
       [0.00e+000, 0.00e+000, 0.00e+000]])

In [24]:
np.empty((3,3)) + np.empty((3,3)) 

Wall time: 0 ns


array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 1.49010199e-320],
       [1.05699242e-307, 0.00000000e+000, 0.00000000e+000]])

In [1]:
list =[1,2,3,4,5,6,7]

In [4]:
np.array(list)

array([1, 2, 3, 4, 5, 6, 7])

In [7]:
x=np.arange(1,100,20)
x

array([ 1, 21, 41, 61, 81])

In [8]:
np.shape(x)

(5,)

In [16]:
z=np.zeros((10,10))
z.shape

(10, 10)

In [23]:
y=z.reshape((2,2,5,5))
y   #now this is a four dimentinal array 

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [24]:
y.dtype

dtype('float64')

In [25]:
y.ndim #how many dimentions 

4

# The above demonstates some common numpy methods and Properties 

# Now Some common Vecrotzed Operations 

In [4]:
a=np.random.randn((10))


In [5]:
b=np.random.randn((10))

In [6]:
a+b

array([-1.6376824 , -0.85466707, -2.8557967 , -0.19505667, -0.74998723,
        0.84289139,  0.03791081,  0.52196366,  0.21827771,  0.60879218])

In [7]:
a*2

array([-1.25788938,  0.03281443, -1.44637045, -1.48748669,  0.95498373,
        0.20018315,  1.38722661, -2.64501037, -0.77109041,  0.27802128])

In [8]:
1/a

array([-1.58996493, 60.94879092, -1.38277162, -1.34454985,  2.09427651,
        9.99085079,  1.44172552, -0.7561407 , -2.59372956,  7.19369405])

In [9]:
a>0

array([False,  True, False, False,  True,  True,  True, False, False,
        True])

In [10]:
a>5

array([False, False, False, False, False, False, False, False, False,
       False])

In [12]:
a[a>0]

array([0.01640722, 0.47749187, 0.10009158, 0.6936133 , 0.13901064])